# Generated by Django 5.0.2 on 2024-02-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeuser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.BooleanField(default=False, verbose_name='Двухфакторная авторизация'),
        ),
    ]
